title = "Plate with Inclusion"

[Rectangle]
L = 10
B = 5

[Ellipse]
ksi = 5 # a = rectangle.B / ksi
a_b = 1 # b = a / a_b

[Material]
Matrix = [1, 0.3]    # [E, nu]
Inclusion = [1, 0.2]

[Mesh]
size = 0.1
refinementFactor = 20
Algorithm = 8
planeStress = false
convertToSquare = false

[Load]
Value = 1

[VTK]
fileName = "PlateWithInclusion.vtu"
Binary = true
