title = "Plate with Inclusion"

[Rectangle]
L = 10
B = 5

[Ellipse]
ksi = 10 # a = rectangle.B / ksi
a_b = 1 # b = a / a_b
convertToSquare = false

[Material]
Matrix = [1, 0.3]    # [E, nu]
Inclusion = [1, 0.2]

[Mesh]
size = 0.2
refinementFactor = 1
Algorithm = 8
planeStress = false

[Load]
Value = 1

[VTK]
fileName = "PlateWithInclusion.vtu"
Binary = true
