title = "Plate with Inclusion"

[Rectangle]
L = 10
B = 10

[Ellipse]
ksi = 10 # a = rectangle.B / ksi
a_b = 3 # b = a / a_b
convertToSquare = false

[Material]
Matrix = [1, 0.3]    # [E, nu]
Inclusion = [2, 0.2]

[Mesh]
size = 1
refinementFactor = 20
Algorithm = 8
planeStress = false

[Load]
Value = 1

[VTK]
fileName = "PlateWithInclusion.vtu"
Binary = true
