title = "Plate with Inclusion"

[Rectangle]
L = 2
B = 0.9

[Ellipse]
ksi = 3 # a = rectangle.B / ksi
b = 0.1

[Material]
Base = [1, 0.3]
Inclusion = [1, 0.2]

[Mesh]
size = 0.05
refinementFactor = 100
Algorithm = 8

[Load]
Value = 1

[VTK]
fileName = "PlateWithInclusion.vtu"
Binary = true